package com.example.patterns.service;

import com.example.patterns.model.DesignPattern;
import com.example.patterns.model.PatternCategory;
import org.springframework.stereotype.Service;

import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
public class DesignPatternService {

    private final List<DesignPattern> patterns = List.of(
            pattern("Singleton", PatternCategory.CREATIONAL, "Ensure a class has one shared instance and provide a global access point.",
                    "Spring beans are singleton scoped by default inside the application context.",
                    "Shared stateless services, configuration holders, caches, and expensive collaborators.",
                    "Global state can hide dependencies and complicate testing.", 95, 2,
                    List.of("Singleton", "Client"),
                    "classDiagram\nclass Client\nclass Singleton {\n  -static instance\n  -Singleton()\n  +getInstance()\n}\nClient --> Singleton : uses"),
            pattern("Factory Method", PatternCategory.CREATIONAL, "Let subclasses or collaborators decide which concrete object to create.",
                    "Bean factories, FactoryBean, and strategy selection based on configuration.",
                    "Object creation varies by runtime condition or product family.",
                    "Adds indirection and can become ceremony for simple construction.", 88, 3,
                    List.of("Creator", "ConcreteCreator", "Product", "ConcreteProduct"),
                    "classDiagram\nclass Creator {\n  +factoryMethod()\n}\nclass Product\nclass ConcreteProduct\nclass ConcreteCreator\nCreator <|-- ConcreteCreator\nProduct <|-- ConcreteProduct\nConcreteCreator --> ConcreteProduct : creates"),
            pattern("Abstract Factory", PatternCategory.CREATIONAL, "Create related families of objects without naming their concrete classes.",
                    "Profiles or configuration classes that produce matching service families.",
                    "Multiple implementations must stay compatible across a product family.",
                    "Can be heavy when only one product varies.", 74, 4,
                    List.of("AbstractFactory", "ConcreteFactory", "AbstractProduct", "ConcreteProduct"),
                    "classDiagram\nclass AbstractFactory {\n  +createRepository()\n  +createNotifier()\n}\nclass CloudFactory\nclass LocalFactory\nclass Repository\nclass Notifier\nAbstractFactory <|-- CloudFactory\nAbstractFactory <|-- LocalFactory\nCloudFactory --> Repository\nCloudFactory --> Notifier"),
            pattern("Builder", PatternCategory.CREATIONAL, "Construct complex objects step by step while keeping construction readable.",
                    "DTO builders, request builders, and immutable configuration objects.",
                    "Objects have many optional fields or validation rules.",
                    "May duplicate fields between the target object and builder.", 86, 2,
                    List.of("Builder", "Product", "Director"),
                    "classDiagram\nclass Report {\n  +title\n  +sections\n}\nclass ReportBuilder {\n  +title()\n  +section()\n  +build()\n}\nclass ReportController\nReportController --> ReportBuilder\nReportBuilder --> Report : builds"),
            pattern("Prototype", PatternCategory.CREATIONAL, "Create new objects by copying an existing prototype.",
                    "Prototype-scoped beans and template objects copied before customization.",
                    "Creation is expensive and objects share a common baseline.",
                    "Deep copying mutable object graphs is easy to get wrong.", 58, 3,
                    List.of("Prototype", "Client", "Clone"),
                    "classDiagram\nclass Client\nclass Prototype {\n  +clone()\n}\nclass ConcretePrototype\nPrototype <|-- ConcretePrototype\nClient --> Prototype : clones"),
            pattern("Adapter", PatternCategory.STRUCTURAL, "Convert one interface into another interface clients expect.",
                    "Wrapping third-party SDKs behind application-specific ports.",
                    "External APIs do not match your domain interface.",
                    "Too many adapters can hide important external behavior.", 91, 2,
                    List.of("Client", "Target", "Adapter", "Adaptee"),
                    "classDiagram\nclass PaymentService\nclass PaymentPort {\n  +charge()\n}\nclass StripeAdapter {\n  +charge()\n}\nclass StripeSdk {\n  +createPayment()\n}\nPaymentService --> PaymentPort\nPaymentPort <|.. StripeAdapter\nStripeAdapter --> StripeSdk"),
            pattern("Bridge", PatternCategory.STRUCTURAL, "Separate abstraction from implementation so both can vary independently.",
                    "Service abstractions combined with interchangeable delivery channels or storage engines.",
                    "Two dimensions of variation would otherwise create many subclasses.",
                    "Introduces extra types that need clear naming.", 61, 4,
                    List.of("Abstraction", "RefinedAbstraction", "Implementor", "ConcreteImplementor"),
                    "classDiagram\nclass Notification\nclass UrgentNotification\nclass Sender {\n  +send()\n}\nclass EmailSender\nclass SmsSender\nNotification <|-- UrgentNotification\nNotification o-- Sender\nSender <|.. EmailSender\nSender <|.. SmsSender"),
            pattern("Composite", PatternCategory.STRUCTURAL, "Treat individual objects and object groups uniformly.",
                    "Menus, permission trees, category hierarchies, and nested workflow steps.",
                    "Clients should work with leaves and containers using the same API.",
                    "Uniform APIs can expose operations that do not make sense for every node.", 72, 3,
                    List.of("Component", "Leaf", "Composite"),
                    "classDiagram\nclass Component {\n  +render()\n}\nclass MenuItem\nclass MenuGroup {\n  +add()\n  +render()\n}\nComponent <|.. MenuItem\nComponent <|.. MenuGroup\nMenuGroup o-- Component"),
            pattern("Decorator", PatternCategory.STRUCTURAL, "Add responsibilities to an object dynamically without changing its class.",
                    "Servlet filters, Spring Security filter chains, and wrapped services.",
                    "Behavior should be composed at runtime in layers.",
                    "Debugging call stacks can become harder.", 79, 3,
                    List.of("Component", "ConcreteComponent", "Decorator"),
                    "classDiagram\nclass Service {\n  +execute()\n}\nclass CoreService\nclass LoggingDecorator\nclass CachingDecorator\nService <|.. CoreService\nService <|.. LoggingDecorator\nService <|.. CachingDecorator\nLoggingDecorator o-- Service\nCachingDecorator o-- Service"),
            pattern("Facade", PatternCategory.STRUCTURAL, "Provide a simple interface over a complex subsystem.",
                    "Application services that coordinate repositories, gateways, validators, and events.",
                    "Controllers need a clean workflow-level API.",
                    "A facade can become a large procedural coordinator.", 93, 2,
                    List.of("Facade", "Subsystem", "Client"),
                    "flowchart LR\nController --> OrderFacade\nOrderFacade --> InventoryService\nOrderFacade --> PaymentGateway\nOrderFacade --> EmailService"),
            pattern("Flyweight", PatternCategory.STRUCTURAL, "Share fine-grained immutable objects to reduce memory usage.",
                    "Caching repeated value objects such as icons, permissions, or formatting styles.",
                    "Many objects repeat the same intrinsic state.",
                    "Separating intrinsic and extrinsic state can reduce readability.", 43, 4,
                    List.of("Flyweight", "FlyweightFactory", "Client"),
                    "classDiagram\nclass Client\nclass StyleFactory {\n  +getStyle()\n}\nclass TextStyle\nClient --> StyleFactory\nStyleFactory --> TextStyle : reuses"),
            pattern("Proxy", PatternCategory.STRUCTURAL, "Control access to another object through a substitute object.",
                    "Spring AOP proxies for transactions, security, caching, and lazy loading.",
                    "Cross-cutting behavior should wrap a target transparently.",
                    "Proxy behavior can surprise callers when boundaries are unclear.", 96, 3,
                    List.of("Subject", "RealSubject", "Proxy"),
                    "classDiagram\nclass AccountService {\n  +transfer()\n}\nclass AccountServiceImpl\nclass TransactionProxy\nAccountService <|.. AccountServiceImpl\nAccountService <|.. TransactionProxy\nTransactionProxy --> AccountServiceImpl"),
            pattern("@Transactional", PatternCategory.SPRING_ARCHITECTURE, "Wrap a service method in a database transaction so all writes commit together or roll back together.",
                    "@Transactional on a service method asks Spring to create a proxy that opens, commits, or rolls back the transaction.",
                    "One business action changes multiple rows and partial success would create messy data.",
                    "It only protects work inside the transaction boundary; remote API calls are not magically rolled back.", 98, 3,
                    List.of("Service Method", "Spring Proxy", "Transaction Manager", "Database"),
                    "sequenceDiagram\nparticipant Browser\nparticipant Service\nparticipant TxProxy as Spring Transaction Proxy\nparticipant DB\nBrowser->>TxProxy: placeOrder()\nTxProxy->>DB: BEGIN\nTxProxy->>Service: run business logic\nService->>DB: save order and items\nalt success\nTxProxy->>DB: COMMIT\nelse exception\nTxProxy->>DB: ROLLBACK\nend"),
            pattern("Saga", PatternCategory.SPRING_ARCHITECTURE, "Coordinate a long business process across services using local transactions and compensating actions.",
                    "Use orchestration with a workflow service, or choreography with events between Spring Boot services.",
                    "A user journey crosses multiple services such as order, payment, inventory, and shipping.",
                    "You must design compensation steps because distributed rollback is not a simple undo button.", 82, 5,
                    List.of("Saga Orchestrator", "Local Transaction", "Compensation", "Events"),
                    "flowchart LR\nOrder[Create Order] --> Payment[Take Payment]\nPayment --> Inventory[Reserve Stock]\nInventory --> Shipping[Book Shipping]\nInventory -. fails .-> Refund[Refund Payment]\nRefund --> Cancel[Cancel Order]"),
            pattern("Outbox", PatternCategory.SPRING_ARCHITECTURE, "Save domain data and the event message in the same database transaction, then publish the message later.",
                    "A Spring service writes an order and an outbox row together; a scheduled publisher or Debezium sends the event to Kafka/RabbitMQ.",
                    "You need reliable events and cannot risk saving data but losing the message.",
                    "Consumers may receive duplicates, so handlers should be idempotent.", 87, 4,
                    List.of("Business Table", "Outbox Table", "Publisher", "Message Broker"),
                    "flowchart LR\nService -->|one transaction| DB[(Database)]\nDB --> Orders[orders table]\nDB --> Outbox[outbox table]\nOutbox --> Publisher[Outbox Publisher]\nPublisher --> Broker[Kafka or RabbitMQ]\nBroker --> Consumer[Other Service]"),
            pattern("Circuit Breaker", PatternCategory.SPRING_ARCHITECTURE, "Stop calling an unhealthy dependency for a while so your app fails fast and recovers calmly.",
                    "Resilience4j circuit breakers wrap RestClient, WebClient, or Feign calls with fallback behavior.",
                    "A downstream service is slow, flaky, or unavailable and repeated calls would exhaust your app.",
                    "Fallbacks must be honest; returning stale or default data is useful only when the business accepts it.", 85, 3,
                    List.of("Closed", "Open", "Half-Open", "Fallback"),
                    "stateDiagram-v2\n[*] --> Closed\nClosed --> Open: failures pass limit\nOpen --> HalfOpen: wait duration ends\nHalfOpen --> Closed: trial calls pass\nHalfOpen --> Open: trial calls fail\nOpen --> Fallback: fail fast"),
            pattern("Chain of Responsibility", PatternCategory.BEHAVIORAL, "Pass a request along handlers until one handles it.",
                    "Servlet filters, Spring Security filters, and validation pipelines.",
                    "Processing has ordered, optional, or short-circuiting steps.",
                    "Order matters and can be difficult to reason about.", 83, 3,
                    List.of("Handler", "ConcreteHandler", "Client"),
                    "flowchart LR\nRequest --> AuthFilter --> RateLimitFilter --> ValidationFilter --> Controller"),
            pattern("Command", PatternCategory.BEHAVIORAL, "Encapsulate a request as an object.",
                    "Job objects, domain commands, undoable actions, and queued work.",
                    "Requests need logging, retrying, scheduling, or undo.",
                    "Can create many small command classes.", 77, 3,
                    List.of("Command", "Invoker", "Receiver"),
                    "classDiagram\nclass Command {\n  +execute()\n}\nclass CreateInvoiceCommand\nclass JobRunner\nclass BillingService\nCommand <|.. CreateInvoiceCommand\nJobRunner --> Command\nCreateInvoiceCommand --> BillingService"),
            pattern("Interpreter", PatternCategory.BEHAVIORAL, "Represent and evaluate a grammar for a small language.",
                    "Search filters, rule expressions, and query DSLs.",
                    "A simple domain language makes repeated rules clearer.",
                    "For complex grammars, use a parser library instead.", 35, 5,
                    List.of("Expression", "TerminalExpression", "NonTerminalExpression", "Context"),
                    "flowchart TD\nExpression --> AndExpression\nExpression --> RoleExpression\nExpression --> RegionExpression\nAndExpression --> RoleExpression\nAndExpression --> RegionExpression"),
            pattern("Iterator", PatternCategory.BEHAVIORAL, "Traverse a collection without exposing its internal structure.",
                    "Java Iterable, streams, repository pagination, and cursor APIs.",
                    "Clients need sequential access to hidden or paged data.",
                    "Concurrent changes and lazy resources need careful lifecycle handling.", 89, 2,
                    List.of("Iterator", "Aggregate", "ConcreteIterator"),
                    "classDiagram\nclass Aggregate {\n  +iterator()\n}\nclass Iterator {\n  +hasNext()\n  +next()\n}\nclass PageIterator\nAggregate --> Iterator\nIterator <|.. PageIterator"),
            pattern("Mediator", PatternCategory.BEHAVIORAL, "Centralize complex communication between objects.",
                    "Application event publishers, workflow coordinators, and message buses.",
                    "Many components interact in tangled ways.",
                    "The mediator can become a hidden god object.", 62, 4,
                    List.of("Mediator", "Colleague"),
                    "flowchart LR\nInventory --> CheckoutMediator\nPayment --> CheckoutMediator\nShipping --> CheckoutMediator\nCheckoutMediator --> OrderEvents"),
            pattern("Memento", PatternCategory.BEHAVIORAL, "Capture and restore an object's previous state without exposing internals.",
                    "Draft saves, undo snapshots, and aggregate history checkpoints.",
                    "Users or workflows need rollback and restore.",
                    "Snapshots can consume storage and may leak sensitive data.", 46, 4,
                    List.of("Originator", "Memento", "Caretaker"),
                    "classDiagram\nclass Editor {\n  +save()\n  +restore()\n}\nclass Snapshot\nclass History\nEditor --> Snapshot : creates\nHistory o-- Snapshot\nEditor --> History"),
            pattern("Observer", PatternCategory.BEHAVIORAL, "Notify dependent objects when state changes.",
                    "Application events, domain events, listeners, and WebSocket updates.",
                    "Several reactions should happen after a state change without tight coupling.",
                    "Event order and transaction timing must be explicit.", 94, 3,
                    List.of("Subject", "Observer", "ConcreteObserver"),
                    "flowchart LR\nOrderService -->|publishes| OrderCreatedEvent\nOrderCreatedEvent --> EmailListener\nOrderCreatedEvent --> AnalyticsListener\nOrderCreatedEvent --> FulfillmentListener"),
            pattern("State", PatternCategory.BEHAVIORAL, "Let an object change behavior when its internal state changes.",
                    "Order, ticket, and workflow lifecycle implementations.",
                    "Conditional behavior depends heavily on lifecycle state.",
                    "State classes can be overkill for small state machines.", 68, 4,
                    List.of("Context", "State", "ConcreteState"),
                    "stateDiagram-v2\n[*] --> Draft\nDraft --> Submitted\nSubmitted --> Paid\nSubmitted --> Cancelled\nPaid --> Shipped\nShipped --> [*]"),
            pattern("Strategy", PatternCategory.BEHAVIORAL, "Define interchangeable algorithms behind one interface.",
                    "Injecting different pricing, sorting, validation, or notification policies.",
                    "The algorithm changes independently from the client.",
                    "Clients still need a selection mechanism.", 97, 2,
                    List.of("Context", "Strategy", "ConcreteStrategy"),
                    "classDiagram\nclass PricingService\nclass DiscountStrategy {\n  +apply()\n}\nclass SeasonalDiscount\nclass LoyaltyDiscount\nPricingService --> DiscountStrategy\nDiscountStrategy <|.. SeasonalDiscount\nDiscountStrategy <|.. LoyaltyDiscount"),
            pattern("Template Method", PatternCategory.BEHAVIORAL, "Define an algorithm skeleton while subclasses fill selected steps.",
                    "Base import jobs, report generation flows, and framework lifecycle hooks.",
                    "The workflow is fixed but individual steps vary.",
                    "Inheritance coupling can make customization rigid.", 66, 3,
                    List.of("AbstractClass", "ConcreteClass"),
                    "classDiagram\nclass ImportJob {\n  +run()\n  #read()\n  #validate()\n  #write()\n}\nclass CsvImportJob\nclass JsonImportJob\nImportJob <|-- CsvImportJob\nImportJob <|-- JsonImportJob"),
            pattern("Visitor", PatternCategory.BEHAVIORAL, "Add operations to an object structure without changing the element classes.",
                    "Exporters, validators, and reporting over stable domain trees.",
                    "The object structure is stable but operations change often.",
                    "Adding new element types becomes more expensive.", 49, 5,
                    List.of("Visitor", "Element", "ConcreteElement"),
                    "classDiagram\nclass Visitor {\n  +visitInvoice()\n  +visitPayment()\n}\nclass ExportVisitor\nclass Element {\n  +accept()\n}\nclass Invoice\nclass Payment\nVisitor <|.. ExportVisitor\nElement <|.. Invoice\nElement <|.. Payment\nInvoice --> Visitor\nPayment --> Visitor")
    );

    public List<DesignPattern> findAll() {
        return patterns.stream()
                .sorted(Comparator.comparing(pattern -> pattern.category().ordinal()))
                .toList();
    }

    public Map<PatternCategory, Long> countByCategory() {
        return patterns.stream()
                .collect(Collectors.groupingBy(DesignPattern::category, Collectors.counting()));
    }

    private static DesignPattern pattern(String name, PatternCategory category, String intent, String springExample,
                                         String whenToUse, String tradeOff, int popularity, int complexity,
                                         List<String> participants, String diagram) {
        return new DesignPattern(name, category, intent, springExample, whenToUse, tradeOff, popularity, complexity, participants, diagram);
    }
}
